version: '2.2'
networks:
  elastic:
    driver: bridge
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    container_name: elastic
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
    volumes:
      - ./plugins:/usr/share/elasticsearch/plugins #插件文件挂载
      - ./data:/usr/share/elasticsearch/data #数据文件挂载
    ports:
      - 9200:9200
    networks:
      - elastic
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.3.3
  #   environment:
  #     SERVER_NAME: kibana
  #     ELASTICSEARCH_HOSTS: "http://elastic:9200"
  #   ports:
  #     - 5601:5601
  #   networks:
  #     - elastic

  docker run -d --name elasticsearch --net elastic -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:8.3.3