version: "2"
networks:
  mysql:
    driver: bridge
services: 
  mysql:
    image: 'mysql'
    ports:
      - '3306:3306'
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root1234
    networks:
      - mysql
  
  redis: 
    image: 'redis'
    ports: 
      - '6379:6379'
    restart: unless-stopped
