version: "2"
networks:
  kafka-net:
    driver: bridge
services:
  zookeeper:
    image: 'wurstmeister/zookeeper'
    networks:
      - 'kafka-net'
    ports:
      - '2181:2181'
    restart: unless-stopped
  kafka:
    image: 'wurstmeister/kafka'
    networks:
      - 'kafka-net'
    ports:
      - '9092:9092'
    environment:
      - DOCKER_API_VERSION=1.22
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
    restart: unless-stopped

